const STATUS_OK = 200;
const STATUS_CREATED = 201;
const STATUS_REQUIRED = 400;
const STATUS_NOT_FOUND = 404;
const STATUS_UNPROC_ENTITY = 422;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  STATUS_REQUIRED,
  STATUS_NOT_FOUND,
  STATUS_UNPROC_ENTITY
}